### ISSUE TITLE
Need excel like drop down selection filter with check box in input field. 

### ISSUE THREAD

**Issue by ashumahajan01** [danny-sg/slickgrid-spreadsheet-plugins#17]
Hello, I am working on one of the requirement, where I need to add a down icon in input field and on click of down icon, excel like drop down selection filter with check box should come. 

Currently the down icon we can see on column header and on click of that icon selection filter will open to select the values to be filter. 
I want the same above functionality in input field. Let me know how we can achieve the same.

**Comment by danny-sg** [comment]
Hi! I'm not developing this it present. I recommend the excellent [ag-grid](https://www.ag-grid.com/). It's got great functionality and good support.
